site_name: Siddhi-IO-Email
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi IO Email: index.md
- API Docs:
  - 1.0.15: api/1.0.15.md
  - 1.0.14: api/1.0.14.md
  - 1.0.13: api/1.0.13.md
  - 1.0.12: api/1.0.12.md
  - 1.0.11: api/1.0.11.md
  - 1.0.10: api/1.0.10.md
  - 1.0.9: api/1.0.9.md
  - 1.0.8: api/1.0.8.md
  - 1.0.7: api/1.0.7.md
  - 1.0.6: api/1.0.6.md
  - 1.0.5: api/1.0.5.md
  - 1.0.4: api/1.0.4.md
  - 1.0.3: api/1.0.3.md
  - 1.0.2: api/1.0.2.md
  - 1.0.1: api/1.0.1.md
  - 1.0.0-M8: api/1.0.0-M8.md
  - 1.0.0-M7: api/1.0.0-M7.md
  - 1.0.0-M6: api/1.0.0-M6.md
  - 1.0.0: api/1.0.0.md
  - latest: api/latest.md
- License: license.md
theme: material
